### ISSUE TITLE
How do we handle SSL? Can we automate SSL to be built-in?

### ISSUE THREAD

**Issue by huntercross** [ponticlaro/docker-templates#1]

**Comment by cristianobaptista** [comment]
A Letsencrypt client can be installed and a cron job can be added to renew the certificates using whatever time interval we see fit, but obviously not all projects will be using free SSL certificates. 
On AWS the load balancer can handle the encrypting so we do not need to add certificates to running docker containers, but on Digital Ocean (and similar) we need to SSH into the server, replace the existing certificates on the host server and then rebuild the containers

**Comment by cristianobaptista** [comment]
As we're moving to Google Cloud, the certificate will always be added to the load balancer (as with AWS), so we usually do not have to deal with this on the Docker container side. All we need to do on the container side is to check the `FORWARDED_PROTO` header so that we redirect to HTTPS if needed.

Even if we have to add a certificate directly into a Docker container, we can install Letsencrypt on the host machine, generate the needed certificate and add a cron job to renew it automatically before it expires. Then we would mount the certificate and its private key using the docker-compose config file whenever the container starts/restarts. This works well for single server projects, which I think it is the only way we would need to add a certificate directly to a Docker container.
